Repository jenkinsci/workflow-basic-steps-plugin, pull requests merged in 2022-01, with the labels that each got.

#162 EOL JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/CatchExecutionOptions.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ToolStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
Labels: dependencies

#145 Migrate from `RestartableJenkinsRule` to `JenkinsSessionRule`
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/EnvStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/FileExistsStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/SleepStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java
Labels: tests

#160 Document pwd(tmp:true) is for the current dir
  src/main/resources/org/jenkinsci/plugins/workflow/steps/PwdStep/help-tmp.html
Labels: documentation

#154 doc [fileExists step] specify that absolute and Windows paths are allowed + add examples
  src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help-file.html
  src/main/resources/org/jenkinsci/plugins/workflow/steps/FileExistsStep/help.html
Labels: documentation

#165 Strengthen `PushdStepTest.restarting` to use an agent
  src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java
Labels: tests

#166 Bump `mock-javamail` from 1.9 to 1.12
  pom.xml
Labels: dependencies

#151 Code cleanups
  src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactUnarchiverStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ArtifactUnarchiverStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/CoreStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/DeleteDirStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/EchoStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/EnvStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ErrorStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/FileExistsStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/GetContextStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/IsUnixStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/PushdStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/PwdStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ReadFileStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/SleepStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/ToolStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/UnstableStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/WarnErrorStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/WithContextStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/stash/UnstashStep.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/ArtifactArchiverStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/CatchErrorStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/EnvStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/FileExistsStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/MailStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/PwdStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/ReadWriteFileStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/SleepStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/TimeoutStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/ToolStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/UnstableStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/WaitForConditionStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/stash/StashTest.java
Labels: chore

#156 Use container agent in `Jenkinsfile`
  Jenkinsfile
Labels: internal
