Repository jenkinsci/workflow-basic-steps-plugin, pull requests merged in 2022-07, with the labels that each got.

#201 Add form validation for `RetryStep.count`
  src/main/java/org/jenkinsci/plugins/workflow/steps/RetryStep.java
Labels: enhancement

#213 [JENKINS-49707] Cleanups after merge of retry base PR
  pom.xml
  src/test/java/org/jenkinsci/plugins/workflow/steps/RetryExecutorStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/RetryStepTest.java
Labels: tests

#168 Migrate to Jakarta Mail
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/steps/MailStep.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/MailStepTest.java
Labels: dependencies

#218 Update plugin BOM
  pom.xml
Labels: dependencies

#219 Analogue of JTH change for `createSpecialEnvSlave`
  src/test/java/org/jenkinsci/plugins/workflow/steps/CoreWrapperStepTest.java
Labels: tests
