Repository jenkinsci/workflow-basic-steps-plugin, pull requests merged in 2023-02, with the labels that each got.

#245 Remove unnecessary SpotBugs exclusion
  src/main/java/org/jenkinsci/plugins/workflow/steps/WriteFileStep.java
Labels: chore

#256 Switch to 2.361.x
  .github/CODEOWNERS
  .github/release-drafter.yml
  .mvn/extensions.xml
  CHANGELOG.md
  Jenkinsfile
  README.md
  pom.xml
Labels: dependencies

#258 Moved `PushdStep` to `workflow-durable-task-step`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/steps/PushdStep.java
  src/main/resources/org/jenkinsci/plugins/workflow/steps/PushdStep/config.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/steps/PushdStep/help-path.html
  src/main/resources/org/jenkinsci/plugins/workflow/steps/PushdStep/help.html
  src/test/java/org/jenkinsci/plugins/workflow/steps/PushdStepTest.java
Labels: removed
